name: issue-events
on:
  issues:
    types: [opened,edited,deleted,closed,reopened,assigned,unassigned,labeled,unlabeled]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - run: echo "new issue event triggered!!"

