name: issue-events
on:
  issues:
    types: [opened, edited,deleted,closed,reopened,assignedunassigned,labeled,unlabeled]
  project_card:
    types: [created, deleted,moved,edited]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - run: echo "new issue event triggered!!"

